// Generated by Speakeasy. Registers this package's MCP servers and skills
// with OpenCode via the plugin config hook.
import { readFileSync, existsSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "platform-mcp")

export const SpeakeasyPlugin = async (_ctx: any) => ({
  config: async (cfg: any) => {
    let mcp: Record<string, any> = {}
    try {
      mcp = JSON.parse(readFileSync(join(ROOT, "mcp.json"), "utf8")).mcp ?? {}
    } catch {
      // A missing or unreadable manifest disables the servers but must not
      // break OpenCode startup.
    }
    for (const server of Object.values(mcp) as any[]) {
      if (!server.headers) continue
      for (const [name, value] of Object.entries(server.headers) as [string, string][]) {
        const resolved = value.replace(/\$\{env:([A-Za-z0-9_]+)\}/g, (_m: string, v: string) => process.env[v] ?? "")
        if (resolved.trim() === "" || resolved.trim() === "Bearer") delete server.headers[name]
        else server.headers[name] = resolved
      }
    }
    cfg.mcp = { ...mcp, ...cfg.mcp }
    const skills = join(ROOT, "skills")
    if (existsSync(skills)) {
      cfg.skills = { ...cfg.skills, paths: [...(cfg.skills?.paths ?? []), skills] }
    }
  },
})

export default SpeakeasyPlugin
