// Generated by Speakeasy. Registers this package's MCP servers and skills
// with OpenCode (V2 transforms, or the V1 config hook via server()).
import { readFileSync, readdirSync, existsSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "speakeasy")
const SKILLS = join(ROOT, "skills")

const loadServers = (): Record<string, any> => {
  let mcp: Record<string, any> = {}
  try {
    mcp = JSON.parse(readFileSync(join(ROOT, "mcp.json"), "utf8")).mcp ?? {}
  } catch {
    // A missing or unreadable manifest disables the servers but must not
    // break OpenCode startup.
  }
  for (const server of Object.values(mcp) as any[]) {
    if (!server.headers) continue
    for (const [name, value] of Object.entries(server.headers) as [string, string][]) {
      const resolved = value.replace(/\$\{env:([A-Za-z0-9_]+)\}/g, (_m: string, v: string) => process.env[v] ?? "")
      if (resolved.trim() === "" || resolved.trim() === "Bearer") delete server.headers[name]
      else server.headers[name] = resolved
    }
  }
  return mcp
}

// V2 disables the whole plugin on an undefined key, so omit a non-plain description.
const parseSkill = (text: string): { description?: string; content: string } => {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text)
  if (!m) return { content: text }
  const content = text.slice(m[0].length)
  const lines = m[1].split(/\r?\n/)
  const i = lines.findIndex((l) => l.startsWith("description:"))
  if (i < 0 || /^[ \t]/.test(lines[i + 1] ?? "")) return { content }
  const raw = lines[i].slice("description:".length).trim()
  const quoted = /^(["'])(.*)\1$/.exec(raw)
  if (!raw || (!quoted && /^[|>"']/.test(raw))) return { content }
  return { description: quoted ? quoted[2] : raw, content }
}

export default {
  id: "speakeasy.speakeasy",
  async setup(ctx: any) {
    const servers = loadServers()
    await ctx.mcp.transform((editor: any) => {
      for (const [name, s] of Object.entries(servers) as [string, any][]) {
        if (editor.get(name)) continue
        editor.set(name, {
          type: "remote",
          url: s.url,
          ...(s.headers ? { headers: s.headers } : {}),
          ...(s.enabled === false ? { disabled: true } : {}),
        })
      }
    })
    if (!existsSync(SKILLS)) return
    await ctx.skill.transform((editor: any) => {
      for (const entry of readdirSync(SKILLS, { withFileTypes: true })) {
        if (!entry.isDirectory() || editor.get(entry.name)) continue
        const path = join(SKILLS, entry.name, "SKILL.md")
        let text: string
        try {
          text = readFileSync(path, "utf8")
        } catch {
          continue
        }
        editor.add({ id: entry.name, name: entry.name, path, ...parseSkill(text) })
      }
    })
  },
  async server() {
    return {
      config: async (cfg: any) => {
        cfg.mcp = { ...loadServers(), ...cfg.mcp }
        if (existsSync(SKILLS)) {
          cfg.skills = { ...cfg.skills, paths: [...(cfg.skills?.paths ?? []), SKILLS] }
        }
      },
    }
  },
}
